name: Rust syntax-v0
on: [push, pull_request]
jobs:
  check:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.85.0
        with:
          components: rustfmt, clippy
      - run: cargo test --locked
      - run: cargo fmt --check
      - run: cargo clippy --locked --all-targets --all-features -- -D warnings
